### PR TITLE
Add Eraser function

### PR DESCRIPTION
**Pull request by markpash**
This is a great project, so I hacked on eraser support. :)

### CODE REVIEW

**Comment by unphased** [comment]
I needed this! Thanks.

**Comment by unphased** [comment]
I tested your branch and it seems to send unterminated messages on the websocket? 
image

**Comment by unphased** [comment]
https://github.com/MarkPash/pipes-and-rust/pull/1

**Comment by markpash** [comment]
> 
> 
> I tested your branch and it seems to send unterminated messages on the websocket?
> image

Good catch, looks like a typo. I force pushed the fixed commit.

**Comment by markpash** [comment]
@unphased @AnyTimeTraveler Please take a look when you have time :)

**Review by AnyTimeTraveler — APPROVED** [review]
Looks good to me.
I'll test it with my rm2 when I'm back home tomorrow and merge if it works for me as well.

Thank you for your contribution!
I've wanted this feature as well.

**Comment by irl-segfault** [comment]
this only supports erasure via the pens with the erase tip (rubber) right?  Not via UI selection of eraser.  Just confirming why it isn't working for me.

**Comment by AnyTimeTraveler** [comment]
Yes, the program only reads what the pen does, not what the drawing program on the tablet does.
For that reason it can't know if the eraser is selected in the UI.

**Comment by irl-segfault** [comment]
cool, thanks for confirming!

**Pull request merged**
